import pygame
#jogo
TAMANHO_JANELA = (1024,760)
JANELA = pygame.display.set_mode(TAMANHO_JANELA)
MARGEM = 80

#cores
PRETO = (0,0,0)
BRANCO = (255,255,255)
AZUL = (0,0,255)

#mapa
LARGURA_MAPA = TAMANHO_JANELA[0] - MARGEM*2
ALTURA_MAPA = TAMANHO_JANELA[1] - MARGEM*2
POSICOES_OCUPADAS = []
BLOCO = min(TAMANHO_JANELA[0] // LARGURA_MAPA, TAMANHO_JANELA[1] // ALTURA_MAPA)
OBJETOS = []